# Combined Deployment and Service YAML (your-application.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-application
  template:
    metadata:
      labels:
        app: your-application
    spec:
      containers:
        - name: your-application-container
          image: your-application-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/your-database-name"

---
apiVersion: v1
kind: Service
metadata:
  name: your-application-service
spec:
  selector:
    app: your-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Change to NodePort or Ingress if needed
